# These are supported funding model platforms

patreon: 3dradspace
paypal: https://www.paypal.com/cgi-bin/webscr?business=3dradspace2@gmail.com&cmd=_xclick&currency_code=EUR&amount=5&item_name=Support development by donating
