name: C++ Windows-x64 Google Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build 3DRadSpace
    uses: ./.github/workflows/cmake-windows-x64.yml
      
  test:
    runs-on: [windows-latest, x64, gpu, self-hosted]
    needs: build
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: cmake-windows-x64
        path: build

    - name: Run tests
      shell: cmd
      working-directory: ${{ github.workspace }}\build\Release\
      run: 3DRadSpace.Tests.exe